# development:
#   adapter: mysql2
#   encoding: utf8
#   database: invndc
#   pool: 5000
#   username: root
#   password: 
#   host: localhost

development:
  adapter: postgresql
  encoding: utf8
  database: invndc
  pool: 5000
  username: postgres
  password: sa
  host: localhost

# test:
#   adapter: mysql2
#   encoding: utf8
#   database: invndccdo_MCA
#   pool: 5000
#   username: root
#   password: 
#   host: localhost

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: invndc
  username: floating-ravine-1607
  password: 
  # host: ec2-54-83-36-203.compute-1.amazonaws.com

# development_localdb:
#   adapter: postgresql
#   encoding: utf8
#   database: imrp
#   port: 5432
#   pool: 5000
#   username: postgres
#   password: sa
#   host: localhost